apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-build
  annotations:
    build.knative.dev/docker-0: {{ .Values.build.registry }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.build.username }}
  password: {{ .Values.build.password }}
